osf/NotoSansOSF-CondensedExtraLight.otd: sans/NotoSans-CondensedExtraLight.otd
	mkdir -p osf
	python osf.py "Condensed" ExtraLight
sans/NotoSans-CondensedExtraLight.otd: sans/NotoSans-CondensedExtraLight.otf
	otfccdump --ignore-hints $< -o $@

osf/NotoSansOSF-SemiCondensedExtraLight.otd: sans/NotoSans-SemiCondensedExtraLight.otd
	mkdir -p osf
	python osf.py "SemiCondensed" ExtraLight
sans/NotoSans-SemiCondensedExtraLight.otd: sans/NotoSans-SemiCondensedExtraLight.otf
	otfccdump --ignore-hints $< -o $@

osf/NotoSansOSF-ExtraLight.otd: sans/NotoSans-ExtraLight.otd
	mkdir -p osf
	python osf.py "" ExtraLight
sans/NotoSans-ExtraLight.otd: sans/NotoSans-ExtraLight.otf
	otfccdump --ignore-hints $< -o $@

osf/NotoSansOSF-CondensedLight.otd: sans/NotoSans-CondensedLight.otd
	mkdir -p osf
	python osf.py "Condensed" Light
sans/NotoSans-CondensedLight.otd: sans/NotoSans-CondensedLight.otf
	otfccdump --ignore-hints $< -o $@

osf/NotoSansOSF-SemiCondensedLight.otd: sans/NotoSans-SemiCondensedLight.otd
	mkdir -p osf
	python osf.py "SemiCondensed" Light
sans/NotoSans-SemiCondensedLight.otd: sans/NotoSans-SemiCondensedLight.otf
	otfccdump --ignore-hints $< -o $@

osf/NotoSansOSF-Light.otd: sans/NotoSans-Light.otd
	mkdir -p osf
	python osf.py "" Light
sans/NotoSans-Light.otd: sans/NotoSans-Light.otf
	otfccdump --ignore-hints $< -o $@

osf/NotoSansOSF-CondensedRegular.otd: sans/NotoSans-CondensedRegular.otd
	mkdir -p osf
	python osf.py "Condensed" Regular
sans/NotoSans-CondensedRegular.otd: sans/NotoSans-Condensed.otf
	otfccdump --ignore-hints $< -o $@

osf/NotoSansOSF-SemiCondensedRegular.otd: sans/NotoSans-SemiCondensedRegular.otd
	mkdir -p osf
	python osf.py "SemiCondensed" Regular
sans/NotoSans-SemiCondensedRegular.otd: sans/NotoSans-SemiCondensed.otf
	otfccdump --ignore-hints $< -o $@

osf/NotoSansOSF-Regular.otd: sans/NotoSans-Regular.otd
	mkdir -p osf
	python osf.py "" Regular
sans/NotoSans-Regular.otd: sans/NotoSans-Regular.otf
	otfccdump --ignore-hints $< -o $@

osf/NotoSansOSF-CondensedMedium.otd: sans/NotoSans-CondensedMedium.otd
	mkdir -p osf
	python osf.py "Condensed" Medium
sans/NotoSans-CondensedMedium.otd: sans/NotoSans-CondensedMedium.otf
	otfccdump --ignore-hints $< -o $@

osf/NotoSansOSF-SemiCondensedMedium.otd: sans/NotoSans-SemiCondensedMedium.otd
	mkdir -p osf
	python osf.py "SemiCondensed" Medium
sans/NotoSans-SemiCondensedMedium.otd: sans/NotoSans-SemiCondensedMedium.otf
	otfccdump --ignore-hints $< -o $@

osf/NotoSansOSF-Medium.otd: sans/NotoSans-Medium.otd
	mkdir -p osf
	python osf.py "" Medium
sans/NotoSans-Medium.otd: sans/NotoSans-Medium.otf
	otfccdump --ignore-hints $< -o $@

osf/NotoSansOSF-CondensedBold.otd: sans/NotoSans-CondensedBold.otd
	mkdir -p osf
	python osf.py "Condensed" Bold
sans/NotoSans-CondensedBold.otd: sans/NotoSans-CondensedBold.otf
	otfccdump --ignore-hints $< -o $@

osf/NotoSansOSF-SemiCondensedBold.otd: sans/NotoSans-SemiCondensedBold.otd
	mkdir -p osf
	python osf.py "SemiCondensed" Bold
sans/NotoSans-SemiCondensedBold.otd: sans/NotoSans-SemiCondensedBold.otf
	otfccdump --ignore-hints $< -o $@

osf/NotoSansOSF-Bold.otd: sans/NotoSans-Bold.otd
	mkdir -p osf
	python osf.py "" Bold
sans/NotoSans-Bold.otd: sans/NotoSans-Bold.otf
	otfccdump --ignore-hints $< -o $@

osf/NotoSansOSF-CondensedExtraBold.otd: sans/NotoSans-CondensedExtraBold.otd
	mkdir -p osf
	python osf.py "Condensed" ExtraBold
sans/NotoSans-CondensedExtraBold.otd: sans/NotoSans-CondensedExtraBold.otf
	otfccdump --ignore-hints $< -o $@

osf/NotoSansOSF-SemiCondensedExtraBold.otd: sans/NotoSans-SemiCondensedExtraBold.otd
	mkdir -p osf
	python osf.py "SemiCondensed" ExtraBold
sans/NotoSans-SemiCondensedExtraBold.otd: sans/NotoSans-SemiCondensedExtraBold.otf
	otfccdump --ignore-hints $< -o $@

osf/NotoSansOSF-ExtraBold.otd: sans/NotoSans-ExtraBold.otd
	mkdir -p osf
	python osf.py "" ExtraBold
sans/NotoSans-ExtraBold.otd: sans/NotoSans-ExtraBold.otf
	otfccdump --ignore-hints $< -o $@

